import diabetes from "./artifacts/diabetes.json";
import cardiovascular from "./artifacts/cardiovascular.json";
import type { ModelArtifact, RiskModel } from "./types";

/**
 * Model artifact loading.
 *
 * Imported statically rather than read from disk at request time: the
 * artifacts are small, they must never be fetchable over the network, and a
 * static import means a missing or malformed artifact fails the build instead
 * of the first patient request.
 *
 * The structural check below runs once per process. It is not defensive
 * programming for its own sake — the artifacts are generated by a separate
 * Python pipeline, so a schema change on that side would otherwise surface as
 * `NaN` in someone's risk score rather than as an error.
 */

const ARTIFACTS: Record<RiskModel, unknown> = {
  diabetes,
  cardiovascular,
};

const validated = new Map<RiskModel, ModelArtifact>();

export function loadArtifact(model: RiskModel): ModelArtifact {
  const cached = validated.get(model);
  if (cached) return cached;

  const artifact = assertWellFormed(ARTIFACTS[model], model);
  validated.set(model, artifact);
  return artifact;
}

export function listModels(): RiskModel[] {
  return ["diabetes", "cardiovascular"];
}

function assertWellFormed(value: unknown, model: RiskModel): ModelArtifact {
  const artifact = value as ModelArtifact;

  if (!artifact || typeof artifact !== "object") {
    throw new Error(`Model artifact for ${model} is missing.`);
  }

  const width = artifact.features?.length;
  if (!width) {
    throw new Error(`Model artifact for ${model} declares no features.`);
  }

  // Every parallel array has to agree on width, or the scorer would silently
  // pair a coefficient with the wrong feature and produce a plausible number
  // that means nothing.
  const widths: Record<string, number | undefined> = {
    coefficients: artifact.coefficients?.length,
    scaled_means: artifact.scaled_means?.length,
    training_means: artifact.training_means?.length,
    "scaler.mean": artifact.scaler?.mean?.length,
    "scaler.scale": artifact.scaler?.scale?.length,
  };

  for (const [field, length] of Object.entries(widths)) {
    if (length !== width) {
      throw new Error(
        `Model artifact for ${model} is inconsistent: ${field} has ${length} ` +
          `entries but there are ${width} features.`,
      );
    }
  }

  // A zero scale would divide by zero and yield Infinity for every patient.
  const degenerate = artifact.scaler.scale.findIndex((s) => !Number.isFinite(s) || s === 0);
  if (degenerate >= 0) {
    throw new Error(
      `Model artifact for ${model} has a non-scaling feature at index ${degenerate}.`,
    );
  }

  if (!Number.isFinite(artifact.intercept) || !Number.isFinite(artifact.base_value)) {
    throw new Error(`Model artifact for ${model} has a non-finite intercept or base value.`);
  }

  return artifact;
}
