-- ===========================================================================
-- AVERIS — model_metrics seed
--
-- Generated by ml/train_all.py. Do not edit by hand; retrain instead.
--
-- Every family that was compared is recorded, not only the one that ships.
-- A patient told they are in a higher-risk range is entitled to see both how
-- well the serving model performs and what it was chosen over.
-- ===========================================================================


-- diabetes (Pima Indians Diabetes)
insert into public.model_metrics
  (model_name, model_version, algorithm, dataset, accuracy, precision, recall, f1_score, roc_auc, is_serving)
values
  ('diabetes', 'v1', 'logistic_regression', 'Pima Indians Diabetes', 0.7143, 0.5926, 0.5926, 0.5926, 0.8080, true),
  ('diabetes', 'v1', 'random_forest', 'Pima Indians Diabetes', 0.7338, 0.5970, 0.7407, 0.6612, 0.8063, false),
  ('diabetes', 'v1', 'xgboost', 'Pima Indians Diabetes', 0.7208, 0.5902, 0.6667, 0.6261, 0.7969, false)
on conflict (model_name, model_version, algorithm) do update set
  accuracy   = excluded.accuracy,
  precision  = excluded.precision,
  recall     = excluded.recall,
  f1_score   = excluded.f1_score,
  roc_auc    = excluded.roc_auc,
  is_serving = excluded.is_serving;

-- cardiovascular (Cleveland Heart Disease)
insert into public.model_metrics
  (model_name, model_version, algorithm, dataset, accuracy, precision, recall, f1_score, roc_auc, is_serving)
values
  ('cardiovascular', 'v1', 'logistic_regression', 'Cleveland Heart Disease', 0.8197, 0.8148, 0.7857, 0.8000, 0.9188, true),
  ('cardiovascular', 'v1', 'random_forest', 'Cleveland Heart Disease', 0.7705, 0.8182, 0.6429, 0.7200, 0.8712, false),
  ('cardiovascular', 'v1', 'xgboost', 'Cleveland Heart Disease', 0.7869, 0.8571, 0.6429, 0.7347, 0.8268, false)
on conflict (model_name, model_version, algorithm) do update set
  accuracy   = excluded.accuracy,
  precision  = excluded.precision,
  recall     = excluded.recall,
  f1_score   = excluded.f1_score,
  roc_auc    = excluded.roc_auc,
  is_serving = excluded.is_serving;
